services:
  - type: web
    name: learnfy
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn learnfy.wsgi --bind 0.0.0.0:$PORT --workers 3"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "learnfy.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: learnfy-db
          property: connectionString
    healthCheckPath: "/"
